name: EarthCore
main: mello.EarthCore
version: ${version}
api-version: "1.21"
author: Mello
softdepend: [dynmap]

commands:
  balance:
    description: Mostra seu saldo
    aliases: [money]
  pay:
    description: Envia dinheiro para outro jogador
    usage: /pay <player> <valor>
  economy:
    description: Comandos administrativos da economia
    usage: /economy <give | take | set | top> [player] [amount]
    permission: economy.admin
  job:
    description: Comandos do sistema de jobs
    usage: /job <list | join | info>
  kingdom:
    description: Comandos de reinos (claims, convites e impostos)
    usage: /kingdom <create | invite | join | claim | unclaim | info | leave | deposit>
  clan:
    description: Comandos de clãs (convites e banco compartilhado)
    usage: /clan <create | invite | join | deposit | withdraw | info | leave>
  claim:
    description: Abre a interface completa de criação de claims
    usage: /claim [confirm|cancel]
  menu:
    description: Abre o menu interativo com atalhos
    usage: /menu
  chat:
    description: Troca entre canais de chat (global, local, clã, cidade e admin)
    usage: /chat <global | local | clan | cidade | admin>
  spawn:
    description: Teleporta para o spawn global
    usage: /spawn
  setspawn:
    description: Define o spawn global na posição atual
    usage: /setspawn
    permission: core.setspawn
  portal:
    description: Configura portais de totem para continentes
    usage: /portal <settarget|settotem> <nome>
    permission: core.portal
  home:
    description: Teleporta para seu home ou define um
    usage: /home [set]
  tpa:
    description: Envia um pedido para teleportar até outro jogador
    usage: /tpa <player>
  tphere:
    description: Envia um pedido para puxar um jogador até você
    usage: /tphere <player>
  msg:
    description: Envia mensagem privada para um jogador
    usage: /msg <player> <mensagem>
  reply:
    description: Responde para o último jogador que você enviou /msg
    usage: /reply <mensagem>
  starterkit:
    description: Recebe o kit inicial manualmente caso tenha perdido os itens
    usage: /starterkit
  shop:
    description: Cria e gerencia sua loja pessoal
    usage: "/shop create|clan create|kingdom create <nome> | /shop confirm"
  register:
    description: Registra uma senha para sua conta.
    usage: "/register <senha> <senha>"
  login:
    description: Faz login com sua conta.
    usage: "/login <senha>"

permissions:
  economy.admin:
    description: Acesso aos comandos administrativos da economia
    default: op
  core.portal:
    description: Permissão administrativa para criar e vincular totems/portais
    default: op
  core.setspawn:
    description: Autoriza definir o spawn global com /setspawn
    default: op
  core.starterkit:
    description: Autoriza o jogador a resgatar o kit inicial pelo comando /starterkit
    default: true
